version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - 9090:9090
    networks:
      - backend
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    deploy:
      mode: global
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning


  alertmanager:
    image: prom/alertmanager:v0.25.0
    networks:
      - backend
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager-data:/data
    command: --config.file=/etc/alertmanager/alertmanager.yml

  mongo:
    image: mongo
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - "http.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - backend

  graylog:
    image: graylog/graylog:4.0
    hostname: graylog-server
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
      - "1514:1514/udp"
    networks:
      - backend
    restart: always
    links:
      - mongo
      - elasticsearch
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/ # trocar pelo IP do seu host 

  web:
    image: nginx
    depends_on:
      - graylog
    networks:
      - backend
    ports:
      - 80:80
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201" # trocar pelo GRAYLOG_IP
        tag: nginxdeploy


  api-astronauta:
    image: api-astronauta:0.1
    ports:
      - 8895:8895
    networks:
      - backend

  chamada-http:
    image: chamada-http:0.1
    ports:
      - 8899:8899
    networks:
      - backend

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:

networks:
  frontend:
  backend:
