{
 "title": "Final",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Informações por Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers Ativos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[1m]))\r\n"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)\r\n"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|web|prometheus\",image!=\"\"}[5m]) * 100, \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.*)\")\r\n\r\n",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(label_replace((container_memory_usage_bytes{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|web|prometheus\", image!=\"\"} - container_memory_cache{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|web|prometheus\", image!=\"\"}), \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.*)\"))\r\n",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Trafego de Entrada por Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name), \"container_name\", \"$1\", \"container_label_compose_service\", \"(.+)\")\r\n\r\n\r\n\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Trafego de Saída por Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}